app = "patesystem"
primary_region = "iad"

[build]

[env]
  PORT = "3000"
  NODE_ENV = "production"
  APP_URL = "https://patesystem.fly.dev"
  SESSION_SECRET = "f71506b9f8a73d7eceb87cfa88a3767fae7a5c44bf5755da14ac497aa19407dd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "patesystem_data"
  destination = "/data"
